//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Palashicheva_PR8.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgencyEntities : DbContext
    {

        public static AgencyEntities _context;

        public AgencyEntities()
            : base("name=AgencyEntities")
        {
        }

        public static AgencyEntities GetContext()
        {
            if (_context == null )
                _context = new AgencyEntities();
            return _context;
        }

    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pol> Pol { get; set; }
        public virtual DbSet<Rezume> Rezume { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
