//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_Palashicheva_PR8.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezume
    {
        public int Id { get; set; }
        public string naimenov { get; set; }
        public string PolID { get; set; }
        public string job { get; set; }
        public decimal money { get; set; }
        public System.DateTime birthdate { get; set; }
        public string city { get; set; }
        public bool pereezd { get; set; }
        public bool experience { get; set; }
        public string komment { get; set; }
    
        public virtual Pol Pol { get; set; }
    }
}
